apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-api
spec:
  selector:
    matchLabels:
      app: count-api
  replicas: 1
  template:
    metadata:
      labels:
        app: count-api
    spec:
      containers:
      - name: count-api
        image: hashicorpnomad/counter-api
        ports:
        - containerPort: 9001
